# lib@home, framework to develop distributed calculations.
# Copyright (C) 2020  Dirk "YouDirk" Lehmann
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


name: Push and pull-request trigger

on:
  push:
    branches:
    - 'master'
    - '**'
    paths:
    - '**'
  pull_request:
    branches:
    - 'master'
    - '**'
    paths:
    - '**'

# Settings
env:
  # ${{secrets.GITHUB_TOKEN}}
  WORKFL_DOCREPO_PATH: doc/libathome
  WORKFL_COMMIT_EMAIL: libathome-bot@users.noreply.github.com
  WORKFL_COMMIT_NAME:  lib@home Bot
  WORKFL_COMMIT_MSG:   Updating API Reference Documetation

# Job are running in parallel
jobs:
  compile-linux:
    name: Compile on Linux
    runs-on: ubuntu-latest
    steps:
      # Checks-out under $GITHUB_WORKSPACE
    - name: Checking out...
      uses: actions/checkout@v2.1.0
      with:
        token: ${{secrets.PUSH_TOKEN}}
        clean: true
        lfs: true
        submodules: true
    - name: Running Make...
      run: |
        cd $GITHUB_WORKSPACE
        make all
      shell: bash

  doc:
    name: API Reference Documentation
    needs: [ compile-linux ]
    runs-on: ubuntu-latest
    steps:
      # Checks-out under $GITHUB_WORKSPACE
    - name: Checking out...
      uses: actions/checkout@v2.1.0
      with:
        token: ${{secrets.PUSH_TOKEN}}
        clean: true
        lfs: true
        submodules: true
    - name: Running Doxygen...
      uses: ./.github/actions/doxygen-environment
      with:
        exec: make doc
    - name: Committing API Reference Documentaion...
      run: |
        cd $GITHUB_WORKSPACE/$WORKFL_DOCREPO_PATH
        git config --local user.email "$WORKFL_COMMIT_EMAIL"
        git config --local user.name  "$WORKFL_COMMIT_NAME"
        git commit -a -m "$WORKFL_COMMIT_MSG"
    - name: Pushing to GitHub...
      uses: ad-m/github-push-action@v0.5.0
      with:
        directory: $GITHUB_WORKSPACE/$WORKFL_DOCREPO_PATH
        repository:
        github_token: ${{secrets.PUSH_TOKEN}}
        branch: master
