# lib@home, framework to develop distributed calculations.
# Copyright (C) 2020  Dirk "YouDirk" Lehmann
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


name: CI

on:
  push:
    branches:
    - 'master'
    paths:
    - '**'
  pull_request:
    branches:
    - 'master'
    paths:
    - '**'

# Settings
env:
  # ${{secrets.GITHUB_TOKEN}}
  WORKFL_DOCREPO_PATH:    'doc/libathome'
  WORKFL_DOCREPO_PUSHDIR: 'YouDirk/libathome-doc'
  WORKFL_COMMIT_EMAIL:    'bot-libathome@users.noreply.github.com'
  WORKFL_COMMIT_NAME:     'Bot'
  WORKFL_COMMIT_MSG:      '[auto] Updating API Reference Documentation'

# Jobs are running in parallel
jobs:
  compile-linux:
    name: Compiles on Linux
    runs-on: ubuntu-latest
    steps:
      # Checking out to $GITHUB_WORKSPACE
    - name: Checking out...
      uses: actions/checkout@v2.1.0
      with:
        token: ${{secrets.PUSH_TOKEN}}
        clean: true
        lfs: false
        submodules: false
    - name: Running Make...
      run: |
        cd $GITHUB_WORKSPACE
        make run ARGS=--version
      shell: bash

  compile-windows:
    name: Compiles on Windows
    runs-on: windows-latest
    steps:
    - name: Installing MSYS2 environment...
      uses: numworks/setup-msys2@v1
      with:
        msystem: MINGW64
        path-type: strict
        update: true
    - name: Installing toolchain...
      run: msys2do pacman -S --noconfirm msys/make wget
                   mingw64/mingw-w64-x86_64-gcc
      # Checking out to $GITHUB_WORKSPACE
    - name: Checking out...
      uses: actions/checkout@v2.1.0
      with:
        token: ${{secrets.PUSH_TOKEN}}
        clean: true
        lfs: false
        submodules: false
    - name: Running Make...
      run: |
        msys2do cd $GITHUB_WORKSPACE
        msys2do make run ARGS=--version

  doc:
    name: API Reference Documentation
    needs: [compile-linux, compile-windows]
    runs-on: ubuntu-latest
    steps:
      # Checking out to $GITHUB_WORKSPACE
    - name: Checking out...
      uses: actions/checkout@v2.1.0
      with:
        token: ${{secrets.PUSH_TOKEN}}
        clean: true
        lfs: false
        submodules: true
    - name: Checking out API Doc master branch...
      run: |
        cd $GITHUB_WORKSPACE/${{env.WORKFL_DOCREPO_PATH}}
        git checkout -f master
        git pull -f
    - name: Running Doxygen...
      uses: ./.github/actions/doxygen-environment
      with:
        exec: make doc
    - name: Committing API Reference Documentation...
      run: |
        cd $GITHUB_WORKSPACE/${{env.WORKFL_DOCREPO_PATH}}
        git config --local user.email "${{env.WORKFL_COMMIT_EMAIL}}"
        git config --local user.name \
          "${{env.WORKFL_COMMIT_NAME}} (from $GITHUB_REPOSITORY)"
        git add .
        git commit -a -m \
          "${{env.WORKFL_COMMIT_MSG}} (for commit $GITHUB_REPOSITORY@$GITHUB_SHA)" \
          || test $? = 1
    - name: Pushing to GitHub...
      uses: ad-m/github-push-action@v0.5.0
      with:
        directory: ${{env.WORKFL_DOCREPO_PATH}}
        repository: ${{env.WORKFL_DOCREPO_PUSHDIR}}
        github_token: ${{secrets.PUSH_TOKEN}}
        branch: master
